const mediaRoot = '/projects/work-import'

export const projects = [
  {
    number: '01',
    slug: '3d-concept',
    name: '3D CONCEPT',
    label: '三维概念设计 · 数字座舱体验',
    eyebrow: '01 · 3D 概念设计',
    title: '3D CONCEPT\nEXPERIENCE.',
    summary: '以车辆、座舱与车机状态为核心，探索三维视觉、动态反馈和情绪化界面之间的融合方式。',
    role: '3D HMI / 概念设计 / 动效',
    year: '2022 — 2026',
    tags: ['3D HMI', 'CONCEPT', 'AUTOMOTIVE'],
    previewVideo: `${mediaRoot}/3d-concept/01-boot-animation.mp4`,
    heroVideo: `${mediaRoot}/3d-concept/01-boot-animation.mp4`,
    gallery: [
      `${mediaRoot}/3d-concept/02-offroad.mp4`,
      `${mediaRoot}/3d-concept/03-climate.mp4`,
      `${mediaRoot}/3d-concept/04-charging.mp4`,
      `${mediaRoot}/3d-concept/05-charging-detail.mp4`,
      `${mediaRoot}/3d-concept/06-light-show.mp4`,
      `${mediaRoot}/3d-concept/07-voyah.mp4`,
    ],
    videos: [],
  },
  {
    number: '02',
    slug: 'ai-exploration',
    name: 'AI EXPLORATION',
    label: 'AI 探索 · 视觉方向研究',
    eyebrow: '02 · AI 探索',
    title: 'AI\nEXPLORATION.',
    summary: '通过 AI 辅助视觉探索，建立面向未来出行体验的图像语言、氛围与概念表达。',
    role: 'AI 视觉探索 / 概念设计',
    year: '2025 — 2026',
    tags: ['AIGC', 'VISUAL RESEARCH', 'CONCEPT'],
    image: `${mediaRoot}/ai-exploration/01-ai-exploration.png`,
    heroImage: `${mediaRoot}/ai-exploration/01-ai-exploration.png`,
    gallery: [
      `${mediaRoot}/3d-concept/08-weichai.mp4`,
    ],
    videos: [],
  },
  {
    number: '03',
    slug: 'motion-design',
    name: 'MOTION DESIGN',
    label: '动效设计 · 交互节奏系统',
    eyebrow: '03 · Motion Design',
    title: 'MOTION\nDESIGN.',
    summary: '从界面转场到微交互节奏，为数字产品建立可感知、可复用的运动语言。',
    role: '动效设计 / 交互原型 / 视觉规范',
    year: '2021 — 2026',
    tags: ['MOTION', 'INTERACTION', 'HMI'],
    previewVideo: `${mediaRoot}/motion-design/01-ui-motion.mp4`,
    heroVideo: `${mediaRoot}/motion-design/01-ui-motion.mp4`,
    gallery: [
      `${mediaRoot}/motion-design/02-motion.mp4`,
      `${mediaRoot}/motion-design/03-motion.mp4`,
      `${mediaRoot}/motion-design/04-motion.mp4`,
      `${mediaRoot}/motion-design/05-motion.mp4`,
      `${mediaRoot}/motion-design/06-motion.mp4`,
      `${mediaRoot}/motion-design/07-motion.mp4`,
      `${mediaRoot}/motion-design/08-motion.mp4`,
      `${mediaRoot}/motion-design/09-motion.mp4`,
      `${mediaRoot}/motion-design/10-motion.mp4`,
      `${mediaRoot}/motion-design/11-motion.mp4`,
    ],
    videos: [],
  },
  {
    number: '04',
    slug: '3d-assets',
    name: '3D ASSETS',
    label: '三维资产 · 场景与模型构建',
    eyebrow: '04 · 3D Assets',
    title: '3D\nASSETS.',
    summary: '围绕模型、材质、灯光与场景构建三维资产，让设计概念以完整的视觉品质被呈现。',
    role: '3D 资产 / 材质灯光 / 场景设计',
    year: '2021 — 2026',
    tags: ['3D ASSETS', 'LOOK DEV', 'VISUALIZATION'],
    image: `${mediaRoot}/3d-assets/05-slide-28.png`,
    heroImage: `${mediaRoot}/3d-assets/05-slide-28.png`,
    gallery: [
      `${mediaRoot}/3d-assets/01-media.mp4`,
      `${mediaRoot}/3d-assets/02-media.mp4`,
      `${mediaRoot}/3d-assets/03-media.mp4`,
      `${mediaRoot}/3d-assets/04-media.mp4`,
      `${mediaRoot}/3d-assets/06-slide-29.png`,
      `${mediaRoot}/3d-assets/07-slide-30.png`,
      `${mediaRoot}/3d-assets/08-slide-35.png`,
      `${mediaRoot}/3d-assets/09-slide-36.png`,
      `${mediaRoot}/3d-assets/10-slide-37.png`,
      `${mediaRoot}/3d-assets/11-slide-38.png`,
    ],
    videos: [],
  },
]

export const projectBySlug = Object.fromEntries(projects.map((project) => [project.slug, project]))
